import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CONTRACT_ABI_PATH = join(__dirname, '../../contracts/artifacts/contracts/MiniWorld.sol/MiniWorld.json');
const OUTPUT_PATH = join(__dirname, '../src/contractABI.ts');

console.log('📄 Copying contract ABI to SDK...');

try {
  // Read contract artifact
  const artifact = JSON.parse(readFileSync(CONTRACT_ABI_PATH, 'utf8'));
  const abi = artifact.abi;
  
  // Generate TypeScript file with ABI
  const content = `/**
 * Contract ABI - Auto-generated during build
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * Generated: ${new Date().toISOString()}
 * Source: contracts/artifacts/contracts/MiniWorld.sol/MiniWorld.json
 * Functions/Events: ${abi.length}
 */

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

  writeFileSync(OUTPUT_PATH, content, 'utf8');
  console.log('✓ Contract ABI copied to SDK');
  console.log(`  ${abi.length} functions/events`);
  console.log(`  Output: ${OUTPUT_PATH}`);
} catch (error) {
  console.error('❌ Failed to copy contract ABI:', error.message);
  console.error('');
  console.error('Make sure contracts are compiled first:');
  console.error('  cd contracts && npx hardhat compile');
  console.error('');
  console.error('Or run the full deployment:');
  console.error('  .\\scripts\\docker-deploy-all.ps1');
  process.exit(1);
}