/**
 * Contract ABI - Auto-generated during build
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file will be populated when you run: npm run build
 * The prebuild script (scripts/copy-abi.js) generates the real ABI.
 */

// Empty ABI for TypeScript to accept this as a module
// This will be replaced during build with the actual contract ABI
export const CONTRACT_ABI: any[] = [];